### PR TITLE
langserver.py: Fix typo

### LINKED ISSUE #30: langserver.py: Fix typo
In the `serve_did_save` function, fix documentation to `Serve for did_save request.`

### PR DESCRIPTION
**Pull request by cominixo01**
Fixed typo on serve_did_save, changes it from did_change --> did_save

This closes #30

### CODE REVIEW

**Comment by ksdme** [comment]
The commit message composition guidelines needs to be follow to keep the code and changes manageable and of greater quality. Please visit http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html. For starters the message should begin with a shortlog such as 'langserver.py: fixed typo' and should end with a reference to the issue.

For short term contributors: we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!
Checklist

    - [ ] I read the commit guidelines and I've followed
    them.
    - [ ] I ran coala over my code locally. (All commits have to pass
    individually. It is not sufficient to have "fixup commits" on your PR,
    our bot will still report the issues for the previous commit.) You will
    likely receive a lot of bot comments and build failures if coala does not
    pass on every single commit!

After you submit your pull request, DO NOT click the 'Update Branch' button.
When asked for a rebase, consult coala.io/rebase
instead.

**Comment by gaocegege** [comment]
@cominixo01 

Hi, is there any update?

**Comment by cominixo01** [comment]
Sorry, just updated the pull request, hope it's good enough!

**Comment by ksdme** [comment]
@cominixo01 Please resolve the conflicting files.

**Comment by ksdme** [comment]
I am sorry that that I did not tell you the proper way to rebase in the earlier comment, but it seems like you merged the branches. Here is what you should do now:

```shell
git reset --hard 042fecb2b9d3fb7183c167cb67eb466a41db51f7
git remote add upstream https://github.com/coala/coala-vs-code.git
git fetch upstream master
git rebase upstream/master
```

This is when you'll encounter a merge conflict. Accept the _current change_ during resolving it. You can do it in a text editor and then make the change you intend to (fixing the typo).

```shell
git status # it should only list langserver.py
git add *
git rebase --continue
```

Your commit will now be the HEAD in your branch. **Please fix your commit message as per the guidelines, refer to http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html**.

You can then push back to your fork and the PR will automatically update.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
Closing abandoned WIP PR.

**Pull request closed without merging**
