### PR TITLE
.gitignore: moban sync

### PR DESCRIPTION
**Pull request by ksdme**
Sync with the current mobans template.

### CODE REVIEW

**Comment by gaocegege** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
shortlog `.gitignore: Sync moban`

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-vs-code/pull/75/commits/272afb6751ad486e2d91a4034973ca523f5b38ed

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
