### PR TITLE
langserver.feature: Fix features of behaviour tests

### LINKED ISSUE #62: Fix features of behave tests
In lanlangserver.feature ```Then it should send a publishDiagnostics request``` should rather be ```Then I should receive a publishDiagnostics type response```.

### PR DESCRIPTION
**Pull request by mach64**
Fixes #62

### CODE REVIEW

**Comment by mach64** [comment]
Dang it! I'm used to the 72 char limit for shortlogs. Should I change it, or leave it be?

**Comment by ksdme** [comment]
Also please visit http://coala.io/rebase for help on rebasing.

**Comment by palash25** [comment]
Can you change your shortlog to `langserver: Fix features of behaviour tests `

I think it will still fall under the 50 char limit

**Comment by mach64** [comment]
Made the changes. Sorry for the late action, was afk for the time.

**Comment by gaocegege** [comment]
ack 90c7857

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
reack https://github.com/coala/coala-vs-code/pull/68/commits/09e424a7be48aef20f2cf314d5332819ed0c01e1

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
