### PR TITLE
docs/images: Add 'logo.png'

### PR DESCRIPTION
**Pull request by Polcat000**
This adds an image file to be used
on the Extension Summary page of VS-Code

Closes https://github.com/coala/coala-vs-code/issues/55

### CODE REVIEW

**Comment by jayvdb** [comment]
@Polcat000 , in your commit message, replace `Added` with `Add`.

**Comment by Polcat000** [comment]
@jayvdb will the gitmate checks automatically restart when a commit is amended? (Sorry, I'm pretty new).

**Comment by Polcat000** [comment]
@jayvdb Corrections made. Can this be merged?

**Comment by Polcat000** [comment]
ack d35a7af

**Comment by gaocegege** [comment]
ack d35a7af

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
unack 4dd209a

**Comment by jayvdb** [comment]
Please update your commit message, appending a blank line and then `Fixes https://github.com/coala/coala-vs-code/issues/55`

**Comment by gaocegege** [comment]
@jayvdb 

No, VS Code won't load the png, and we should change here: https://github.com/coala/coala-vs-code/blame/master/vscode-client/README.md#L3

I use the https://api.coala.io/en/latest/_static/images/coala_logo.svg as the logo for coala, and I think the PR could also update here, or we could open a new newcomer issue for it.

**Comment by Polcat000** [comment]
@jayvdb @gaocegege I apologize, adding the image wont fix #55.
 My plan was to add the image and then figure out how to plug it in to the VS Code client. I can still try to solve this myself, but it will take me some time.

**Comment by jayvdb** [comment]
@Polcat000 , if you want to only add the image to the README, we can merge that.

Then the issue of the VS Code client can be worked on by someone else, or you could do it later.

**Comment by jayvdb** [comment]
Closing as this doesnt yet solve the problem, and we now use `moban` to copy/sync images from other repos in a verifiable way.

**Pull request closed without merging**
